api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "27675032591f48d242d557e81cc7b397615ab54db05fa36bfc53884c67160a09"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.211.tar.gz"
    source_sha256 = "c2a73abeb1b2a2ca7ba970d0a9426c272e1fe66f40ca41fcc120cc5d64fd4b01"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.211/node-engine-0.0.211.tgz"
    version = "0.0.211"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "1eb059f5a465ef76e2ed65a8b0464d16b893462caf81b0bacc02237a0af9d749"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.43.tar.gz"
    source_sha256 = "eb33fb109820c242fbfe76aa9ed4b0c1f8d459834b9e57b3903799d48b355de7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.43/npm-0.1.43.tgz"
    version = "0.1.43"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "39845d9d5aabde986b1fd507f1d098e516d6f4eada6a1ba4338866f23fb2bcb8"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.49.tar.gz"
    source_sha256 = "ffcaca50f9adb97aed49a386e0b67de7084d5714d70c913b161072a9244d47fc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.49/yarn-install-0.1.49.tgz"
    version = "0.1.49"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.211"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.49"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.211"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.43"
