api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Paketo Buildpack for Node.js"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/nodejs/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.3"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.0.2"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.0.4"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.2.7"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.1.10"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.2.10"

  [[order.group]]
    id = "paketo-buildpacks/yarn-start"
    optional = true
    version = "2.2.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.3"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.0.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.0.4"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.1.10"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.2.10"

  [[order.group]]
    id = "paketo-buildpacks/npm-start"
    optional = true
    version = "2.1.22"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.3"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.0.2"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    version = "2.2.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.1"
