api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "4b374613aa343103daa4d89af30e8d77e5e0bf3e85ea4686a1294179cc8b25ec"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.230.tar.gz"
    source_sha256 = "6a7b3a7da69df25ba77211d9d4be9ee6ce291702d4a8b368ec6ddd8244e95b52"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.230/node-engine-0.0.230.tgz"
    version = "0.0.230"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "af1cb4e56f540173e3105705236874278089b36df16addc5ed34b197714e6cfd"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.54.tar.gz"
    source_sha256 = "d92e61fd46349322d16bed2c6184e833770520226614feb42f774b5f2335a77b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.54/npm-0.1.54.tgz"
    version = "0.1.54"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "15deef6ffc5e343f7a6a3dfec23fb4646191c47f7bf32c87b3999f07d11203db"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.63.tar.gz"
    source_sha256 = "59b61dee7957ceeca114fb85dba135b3e689eb9f4c131d7a6f7581291d78c5c5"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.63/yarn-install-0.1.63.tgz"
    version = "0.1.63"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.230"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.63"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.230"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.54"
