api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Paketo Buildpack for Node.js"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/nodejs/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.2.2"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "4.1.6"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "1.3.11"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.0.5"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "1.0.24"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.0.6"

  [[order.group]]
    id = "paketo-buildpacks/yarn-start"
    optional = true
    version = "2.0.5"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.1"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "5.19.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.2.2"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "4.1.6"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "1.4.8"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "1.0.24"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.0.6"

  [[order.group]]
    id = "paketo-buildpacks/npm-start"
    optional = true
    version = "2.0.6"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.1"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "5.19.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.2.2"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "4.1.6"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    version = "2.0.6"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.1"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "5.19.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.1"
