api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "27675032591f48d242d557e81cc7b397615ab54db05fa36bfc53884c67160a09"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.211.tar.gz"
    source_sha256 = "c2a73abeb1b2a2ca7ba970d0a9426c272e1fe66f40ca41fcc120cc5d64fd4b01"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.211/node-engine-0.0.211.tgz"
    version = "0.0.211"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "c33164be669dbea2f72f534bd3c38411689cab036ecd1d43bf9064b0eeb51edf"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.39.tar.gz"
    source_sha256 = "b409596bf64d859859e3976f137b38f2fd1a523f52c249018e6c479df04139eb"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.39/npm-0.1.39.tgz"
    version = "0.1.39"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "3b17abd5ffd007ca0d413bb5119da95fddcdb2b54e8ce946c4625e1e987babee"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.50.tar.gz"
    source_sha256 = "f7326da06dcf85ec1f878414b93f6698e348b7d53fd862d66f4335ba33003eef"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.50/yarn-install-0.1.50.tgz"
    version = "0.1.50"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.211"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.50"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.211"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.39"
