api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "06fb7908a1c78312bc4cb19b563a36b66cc91d0d223edee7f3210de0da379442"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.221.tar.gz"
    source_sha256 = "e22dfc7570837f1e7e787a839e00320acfca447459361b701d59c4ba773a2540"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.221/node-engine-0.0.221.tgz"
    version = "0.0.221"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "0b12072d2825a419c2ab6f8157e5f76239df82dcd48cfefa173e9de44b3dcaef"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.46.tar.gz"
    source_sha256 = "ec030827cdb9790ad9342e931c1bcfb664d5b91fe46f1b5cb3996c0040817147"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.46/npm-0.1.46.tgz"
    version = "0.1.46"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "fc38a604df2dcc8dafefce6d3fab28c419ccf8486fb3df7c69a2bbd34ada5635"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.55.tar.gz"
    source_sha256 = "0e53d7a6d733bbebf523df4ed9922045caf23eda5075e234a7c79a69e3c9f4b9"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.55/yarn-install-0.1.55.tgz"
    version = "0.1.55"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.221"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.55"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.221"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.46"
