api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Paketo Node.js Buildpack"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "2.1.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.2.2"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "0.1.2"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.2.5"

  [[order.group]]
    id = "paketo-buildpacks/yarn-start"
    version = "0.0.5"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.1.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.0.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "3.0.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "2.1.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.2.2"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "0.2.7"

  [[order.group]]
    id = "paketo-buildpacks/npm-start"
    version = "0.1.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.1.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.0.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "3.0.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "2.1.0"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.2.2"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    version = "0.1.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.1.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.0.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "3.0.0"
