api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "2b337dfb196d216922782b6776a49d40fd849189248ae1b2ae64070cf898e83b"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.222.tar.gz"
    source_sha256 = "5139d671ea35615e17935f86fd2bc0890240cd01c051d37c0f26be06f560b9df"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.222/node-engine-0.0.222.tgz"
    version = "0.0.222"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "61f88425725fb91d2ec2c54695aec1d14c115552015579a8ee157c643fa0ea70"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.48.tar.gz"
    source_sha256 = "6da2786715e9db8f5c816050d5ab08a598ada95cf48d529284b1ece9a6722099"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.48/npm-0.1.48.tgz"
    version = "0.1.48"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "f27e4f0ece3cf15500218ec3e5f31db4cd48b673dcf45d120275c23666ccd6b8"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.56.tar.gz"
    source_sha256 = "bf3715a25ec7276df6aa179961c15724cb0b5f351970e56a67897c17287bd569"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.56/yarn-install-0.1.56.tgz"
    version = "0.1.56"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.222"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.56"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.222"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.48"
