api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "7b3cc16764d2fe66deeac1c43e8b7232b84e48a22adb26edb23a71f84d5cb928"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.229.tar.gz"
    source_sha256 = "66e464b67f2390c5a88f4d6dd7c88650a777af383eb8fd22861db3a079d0d5a8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.229/node-engine-0.0.229.tgz"
    version = "0.0.229"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "af1cb4e56f540173e3105705236874278089b36df16addc5ed34b197714e6cfd"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.54.tar.gz"
    source_sha256 = "d92e61fd46349322d16bed2c6184e833770520226614feb42f774b5f2335a77b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.54/npm-0.1.54.tgz"
    version = "0.1.54"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "43c72d800f8ccbba3fd4e3850ab07191d8c765a76aa87f647bba043c58f7dce4"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.62.tar.gz"
    source_sha256 = "50ee89ccaf601066907dc84b749129b605bf7b3b4505627d4fbae12be155f82e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.62/yarn-install-0.1.62.tgz"
    version = "0.1.62"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.229"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.62"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.229"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.54"
