api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Paketo Buildpack for Node.js"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/nodejs/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.4"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    optional = true
    version = "1.17.8"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.8.0"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    version = "2.2.4"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "2.6.4"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.4"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.5.4"

  [[order.group]]
    id = "paketo-buildpacks/yarn-start"
    optional = true
    version = "2.4.4"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.4"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    optional = true
    version = "1.17.8"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.8.0"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    version = "2.1.0"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.3.4"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    optional = true
    version = "2.5.4"

  [[order.group]]
    id = "paketo-buildpacks/npm-start"
    optional = true
    version = "2.3.4"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.5.4"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    optional = true
    version = "1.17.8"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "7.8.0"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
    version = "2.5.4"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"
