api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.257"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.84"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.257"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.76"
