api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "cab3a1172c4cdf1fe7e3647568657ab56de51d3074ee3941393de9db25dc24b4"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.209.tar.gz"
    source_sha256 = "74e37e925a8b44f4376dcb11daed6e766488fc6a4084e66bc82572fddb8f2bc4"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.209/node-engine-0.0.209.tgz"
    version = "0.0.209"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "708e91ddf03c4015ef007a4cd2dae0d43feeb1f75ea50cfad8c2a0a4ace505bd"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.33.tar.gz"
    source_sha256 = "219905edb02c473f9632ba504a76e1342816b8cc8c3ff26ee9be5db86fc7adce"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.33/npm-0.1.33.tgz"
    version = "0.1.33"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "ee259e6a920ae55f1ed8ac97dc535fdadbeaff3fa5620b86e3acfbbde2a28c4b"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.43.tar.gz"
    source_sha256 = "fbb19fefb3a1e3b49ac856718b383f3e73630202501d430a684bdcead9d3aeed"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.43/yarn-install-0.1.43.tgz"
    version = "0.1.43"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.209"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.43"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.209"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.33"
