api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "2861daa754ccdea292549507bf26936bc63719cd7df87067abc44310501ce19d"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.227.tar.gz"
    source_sha256 = "d53c5ced3ca50622f0b2d4b5e0227cf931cf4a1b0568d4c2d730a757575c8e07"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.227/node-engine-0.0.227.tgz"
    version = "0.0.227"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/npm"
    sha256 = "29d2e6112d557c672682457d33df0987c8d5e211eb95d6ded761cf422979042e"
    source = "https://github.com/paketo-buildpacks/npm/archive/v0.1.53.tar.gz"
    source_sha256 = "0388af1878433af8e53a94b0bb4d3900b48da5943458e5441ab046fad40f71fe"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.53/npm-0.1.53.tgz"
    version = "0.1.53"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/yarn-install"
    sha256 = "ad175d48af3fd4dba5983e5436a102cf63d3b4c63edd6dab3eb75251648587a2"
    source = "https://github.com/paketo-buildpacks/yarn-install/archive/v0.1.58.tar.gz"
    source_sha256 = "5d9cd4d884679ba81392639310736bede2a5d55aeb65aba01fb650ec31e7c1df"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.58/yarn-install-0.1.58.tgz"
    version = "0.1.58"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.227"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    version = "0.1.58"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.227"

  [[order.group]]
    id = "paketo-buildpacks/npm"
    version = "0.1.53"
